_1_2_Mutiple_Exception_handling.py